name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    name: ${{ matrix.os }} • ${{ matrix.arch }} • ${{ matrix.cmake_build_type }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        cmake_build_type: [Release]
        include:
          - os: ubuntu
            arch: x86_64
            runner: ubuntu-22.04
          - os: ubuntu
            arch: arm64
            runner: ubuntu-22.04-arm
          - os: macos
            arch: x86_64
            runner: macos-13
          - os: macos
            arch: arm64
            runner: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Configure (CMake)
        run: cmake -S . -B build -DBUILD_TESTS=ON -DBUILD_EXAMPLES=ON -DCMAKE_BUILD_TYPE=${{ matrix.cmake_build_type }}

      - name: Build
        run: cmake --build build -j

      - name: Test (CTest)
        run: cd build && ctest --output-on-failure


